add support for token based access
zmallen/pygraylog pull request #8
Opened 2017-04-19 10:54 UTC by jafferli

add support for token based access api

2017-04-19 12:44 UTC, zmallen commented on pygraylog/graylogapi.py
> +        if username is not None and api_key is not None:
This check is raising an error in the unit tests. My question is: should it not matter if the username, password and api_key are set? We could just prefer the API key if it is provided, which is what seems like you added on line 42.

2017-04-19 12:45 UTC, zmallen commented on pygraylog/graylogapi.py
> +            payload = self.api_key + ':token'
👍  this looks like the way Graylog constructs the token header, http://docs.graylog.org/en/2.2/pages/configuration/rest_api.html

2017-04-19 12:46 UTC, zmallen requested changes
I think the authorization header looks correct, and it matches documentation. Thanks for the P/R!

Could you please add some unit tests and fix the current broken unit test? It throws an exception since we generate a Graylog Object w/ username/password & an API key. I would split that unit test into a username/password one and a token based one. Lastly, could you increment `setup.py` version of pygraylog so I can do a pypi release?

Thank you!

2017-04-19 12:48 UTC, zmallen commented
One last observation - update readme to show token based auth as well!

2017-04-20 03:33 UTC, jafferli commented
update the patch-1 branch for
1) setup.py for version change to 0.3.2
2) unit test item

2017-04-20 14:07 UTC, zmallen approved these changes

2017-04-20 14:07 UTC, zmallen commented
Thank you @jafferli ! I'll get this pushed to pypi asap

2017-04-20 14:07 UTC, merged